version: '3'
services:
  discovery:
    image: discovery:latest
    ports:
      - 1111:1111
  producer-profile:
    image: producer-profile:v1
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:1111/eureka
    # restart: on-failure
    depends_on:
      - discovery
    ports:
      - 2222:2222
  consumer-profile:
    image: consumer-profile:v1
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:1111/eureka
    depends_on:
      - discovery
    ports:
      - 8080:8080