---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: producer
  name: producer
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: producer
  strategy: 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: producer
    spec:
      containers:
      - image: gcr.io/automatic-hawk-276011/producer-profile:v1
        name: producer
        env:
        - name: JAVA_OPTS
          value: >-
                -DEUREKA_SERVER=http://discovery:1111/eureka
        ports:
        - name: main
          protocol: TCP
          containerPort: 2222
      
---

apiVersion: v1
kind: Service
metadata:
  name: producer
  labels:
    app: producer
spec:
  selector:
    app: producer
  type: LoadBalancer
  ports:
  - port: 2222
    protocol: TCP
    targetPort: 2222
