FROM openjdk:8-jdk-alpine
COPY ./target/MicroserviceDiscoveryServer-0.0.1-SNAPSHOT.jar MicroserviceDiscoveryServer-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","MicroserviceDiscoveryServer-0.0.1-SNAPSHOT.jar"]